
services:
  db:
    image: postgres:latest
    container_name: ProgAvanzadaBD
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Qwerty1!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - C:\docker\postgres:/var/lib/postgresql/data
    networks:
      - prog-net

  app:
    build: ./app
    container_name: progavanzada-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Qwerty1!
    depends_on:
      - db
    networks:
      - prog-net

networks:
  prog-net:
    driver: bridge
